### ISSUE TITLE
Incorrect execution location when using WSL/Remote Development

### ISSUE THREAD

**Issue by christianfosli** [ArturoDent/command-alias#7]
In order to use this extension when using vs code's remote development feature to program on WSL Linux but run the UI in windows I had to edit my user settings to override the extension kind, for this extension:

```
    "remote.extensionKind": {
        "ArturoDent.command-alias": [
            "ui"
        ]
    }
```

Otherwise the extension first does not get enabled when using remote development:
![image](https://github.com/ArturoDent/command-alias/assets/36294671/142b5a49-68f8-40a5-86bf-537673327cc0)

Or if I do install it in vs-code WSL it is stuck complaining about "Reload Required", even if I keep reloading and restarting vscode:
![image](https://github.com/ArturoDent/command-alias/assets/36294671/eaeeafd5-8ad1-4a78-ab16-59e66d1a2310).

**Comment by ArturoDent** [comment]
Closed with v0.6.2.  


Added 

```json
 "extensionKind": [
  "ui",
  "workspace"
 ],
```
